"""
test_ax
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print('Hello Sasha')

@aql.dataframe(task_id="python_2")
def python_2_func():
    print('Hello Renata')

default_args={
    "owner": "Александр Видякин,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-08-05", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Александр Видякин": "mailto:alekskek@mail.ru",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clz86c7jw11rw01kxgni9st9b/cloud-ide/clzgqsb3v0t7001jwlv0k4bf8/clzgqsofu0tzu01jtdjwnbpn0",
    },
)
def test_ax():
    python_1 = python_1_func()

    python_2 = python_2_func()

    python_2 << python_1

dag_obj = test_ax()
